VideoCategory.create(category: 1, name: "映画とアニメ")
VideoCategory.create(category: 2, name: "自動車と乗り物")
VideoCategory.create(category: 10, name: "音楽")
VideoCategory.create(category: 15, name: "ペットと動物")
VideoCategory.create(category: 17, name:　"スポーツ")
VideoCategory.create(category: 19, name:　"旅行とイベント")
VideoCategory.create(category: 20, name:　"ゲーム")
VideoCategory.create(category: 22, name:"ブログ")
VideoCategory.create(category: 23, name:"コメディー")
VideoCategory.create(category: 24, name:"エンターテイメント")
VideoCategory.create(category: 25, name:"ニュースと政治")
VideoCategory.create(category: 26, name:"ハウツーとスタイル")
VideoCategory.create(category: 27, name:"教育")
VideoCategory.create(category: 28, name:"科学と技術")